name: Deno CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Test app

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Check formatting
        run: deno fmt --check --unstable ignore=build,dist,README.md

      - name: Run tests
        run: deno test --allow-read --allow-write
